spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: svc-clientes
        uri: lb://svc-clientes
        predicates:
          - Path=/clientes/**
        filters:
          - StripPrefix=1
      - id: svc-productos
        uri: lb://svc-productos
        predicates:
          - Path=/productos/**
        filters:
          - StripPrefix=1
      - id: svc-ventas
        uri: lb://svc-ventas
        predicates:
          - Path=/ventas/**
        filters:
          - StripPrefix=1
      - id: svc-usuarios
        uri: lb://svc-usuarios
        predicates:
          - Path=/usuarios/**
        filters:
          - StripPrefix=1
      - id: svc-oauth
        uri: lb://svc-oauth
        predicates:
          - Path=/api/security/**
        filters:
          - StripPrefix=2