INSERT INTO TB_ROLES (DES_ROL) VALUES('ROLE_ADMIN');
INSERT INTO TB_ROLES (DES_ROL) VALUES ('ROLE_USER');
INSERT INTO TB_ROLES (DES_ROL) VALUES('ROLE_ESPECIAL');

INSERT INTO TB_USUARIOS (APELLIDOS,COD_EMPRESA,USUARIO,NOMBRES,COD_USUARIO_REGISTRO,PASSWORD,CORREO_EMPRESA, CORREO_PERSONAL, ID_ROL, IND_BAJA,FEC_REGISTRO) VALUES ('MARCOS','XXXXX','cmarcos','CESAR',1,'$2a$10$BzLfJnkkwTvR1PDdvectleeIZeMCYics3W5vrR45MscE/oqQI51hG','cmarcos@rewardsperu.com','cmarcos@rewardsperu.com',1,'N', NOW());
INSERT INTO TB_USUARIOS (APELLIDOS,COD_EMPRESA,USUARIO,NOMBRES,COD_USUARIO_REGISTRO,PASSWORD,CORREO_EMPRESA, CORREO_PERSONAL, ID_ROL,IND_BAJA,FEC_REGISTRO) VALUES ('PALACIOS','XXXXX','dpalacios','DANIEL',1,'$2a$10$BzLfJnkkwTvR1PDdvectleeIZeMCYics3W5vrR45MscE/oqQI51hG','','',3,'N', NOW());
INSERT INTO TB_USUARIOS (APELLIDOS,COD_EMPRESA,USUARIO,NOMBRES,COD_USUARIO_REGISTRO,PASSWORD,CORREO_EMPRESA, CORREO_PERSONAL, ID_ROL,IND_BAJA,FEC_REGISTRO) VALUES ('PORTILLO','XXXXX','lportillo','LIZBETH',1,'$2a$10$BzLfJnkkwTvR1PDdvectleeIZeMCYics3W5vrR45MscE/oqQI51hG','','',2,'N', NOW());
INSERT INTO TB_USUARIOS (APELLIDOS,COD_EMPRESA,USUARIO,NOMBRES,COD_USUARIO_REGISTRO,PASSWORD,CORREO_EMPRESA, CORREO_PERSONAL, ID_ROL,IND_BAJA,FEC_REGISTRO) VALUES ('DAVILA','XXXXX','adavila','JAIME',1,'$2a$10$BzLfJnkkwTvR1PDdvectleeIZeMCYics3W5vrR45MscE/oqQI51hG','','',2,'N', NOW());